import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { TodoForm, TodoList } from '../features/todos/index';
import styles from '../styles/sass/index.module.scss';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <main className={styles.main}>
        <h1>ToDo App</h1>
        <h2>Search ToDo</h2>
        <Link href={'/todos/form'}>Create ToDo</Link>
        <TodoList />
      </main>
    </>
  );
};

export default Home;
